name: Prebuild
on:
  release:
    types: [published]
permissions:
  contents: write

jobs:
  prebuild:
    runs-on: windows-latest

    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node.js
        uses: actions/setup-node@v6

      - name: Install node_modules
        run: npm ci

      - name: Prebuild
        run: npm run prebuildify

      - name: Generate x64 attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: prebuilds/win32-x64/@indutny+simple-windows-notifications.node

      - name: Prebuild arm64
        run: npm run prebuildify -- --arch arm64

      - name: Generate arm64 attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: prebuilds/win32-arm64/@indutny+simple-windows-notifications.node

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: prebuilds
          path: prebuilds/*

  publish:
    name: Publish

    runs-on: windows-latest

    needs: prebuild

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node.js
        uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org/'

      - run: npm install -g npm@latest

      - name: Download built libraries
        uses: actions/download-artifact@v8
        with:
          pattern: prebuilds
          path: prebuilds
          merge-multiple: true

      - name: Install node_modules
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - run: npm test
        env:
          PREBUILDS_ONLY: 1

      - name: Publish
        run: npm publish --access public --provenance
