name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [lts/*, latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test

  windows2019:
    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [lts/*, latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test

  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*, latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test
